config-version: 2

name: "jaffleShop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

#dbt-cloud:
  # project-id: 275557 # Put your project id here

profile: dsJaffleShop # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["dataTests"]
seed-paths: ["seeds", "jaffleData"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbtPackages"

vars:
  "dbtDate:timeZone": "America/Los_Angeles"

seeds:
  jaffleShop:
    +schema: dsJaffleShop

models:
  jaffleShop:
    staging:
      +materialized: view
    marts:
      +materialized: table