semantic_models:
  - name: products
    description: |
      Product dimension table. The grain of the table is one row per product.
    model: ref('products')
    entities:
      - name: product
        type: primary
        expr: product_id
    dimensions:
      - name: product_name
        type: categorical
      - name: product_type
        type: categorical
      - name: product_description
        type: categorical
      - name: is_food_item
        type: categorical
      - name: is_drink_item
        type: categorical
      - name: product_price
        type: numeric