semantic_models:
  #The name of the semantic model.
  - name: products
    description: |
      Product dimension table. The grain of the table is one row per product.
    #The name of the dbt model and schema
    model: ref('products')
    #Entities. These usually correspond to keys in the table.
    entities:
      - name: product
        type: primary
        expr: productId
    #Dimensions. Either categorical or time. These add additional context to metrics. The typical querying pattern is Metric by Dimension.
    dimensions:
      - name: productName
        type: categorical
      - name: productType
        type: categorical
      - name: productDescription
        type: categorical
      - name: isFoodItem
        type: categorical
      - name: isDrinkItem
        type: categorical
      - name: productPrice
        type: categorical